services:
  webhook:
    build:
      context: ../..
      dockerfile: src/FinanceApi.Webhook/Dockerfile
    container_name: finance-webhook
    ports:
      - "8080:8080"
    environment:
      - Kafka__BootstrapServers=172.31.48.78:9092
      - Pluggy__ClientId=${PLUGGY_CLIENT_ID}
      - Pluggy__ClientSecret=${PLUGGY_CLIENT_SECRET}
      - Serilog__WriteTo__0__Name=Console
      - APP_INSTANCE=EC2-4 | WEBHOOK | 172.31.57.127
    restart: unless-stopped
